-- 1
SELECT ACC_NAME, ACC_RATING
FROM ACCOUNT
WHERE ACC_RATING < 5
ORDER BY ACC_RATING;

-- 2
SELECT T_DATE, E_NAME
FROM TRANSACTION
INNER JOIN EMPLOYEE
ON T_E_KTP_NUM = E_KTP_NUM
WHERE MONTH(T_DATE) = 8 AND YEAR(T_DATE) = 2020;

-- 3
SELECT MONTHNAME(T_DATE), YEAR(T_DATE), COUNT(*)
FROM TRANSACTION
GROUP BY YEAR(T_DATE), MONTH(T_DATE)
ORDER BY COUNT(*) DESC;

-- 4
SELECT ACC_NAME, SUM(T_LOAN) AS 'TOTAL PEMINJAMAN'
FROM ACCOUNT
LEFT JOIN TRANSACTION
ON ACC_KTP_NUM = T_ACC_KTP_NUM
GROUP BY ACC_KTP_NUM
ORDER BY SUM(T_LOAN) DESC;

-- 5
SELECT ACC_NAME, T_ID, SUM(SISA)
FROM ACCOUNT, 
(
    SELECT *, COUNT(LP_ID), (LT_PERIOD - COUNT(LP_ID)) AS SISA
    FROM TRANSACTION
    INNER JOIN LOAN_TYPE
    ON T_LT_ID = LT_ID
	LEFT JOIN LOAN_PAYMENT
    ON LP_T_ID = T_ID
    WHERE T_STATUS = 'BELUM LUNAS'
    GROUP BY T_ID
    ORDER BY SISA
) AS SC
WHERE T_ACC_KTP_NUM = ACC_KTP_NUM
GROUP BY ACC_KTP_NUM
ORDER BY SUM(SISA) DESC;