-- 1
SELECT ACC_KTP_NUM, ACC_NAME
FROM account
WHERE ACC_KTP_SCAN IS NULL 
OR ACC_NPWP_SCAN IS NULL 
OR ACC_SELFIE IS NULL 
OR ACC_BANK_NUM_SCAN IS NULL;

-- 2
SELECT ACC_KTP_NUM, ACC_NAME
FROM loan_type lt
INNER JOIN transaction tr ON tr.T_LT_ID = lt.LT_ID
INNER JOIN account ac ON ac.ACC_KTP_NUM = tr.T_ACC_KTP_NUM
WHERE LT_NAME = '12 BULAN';

-- 3
SELECT ACC_KTP_NUM,ACC_NAME, COUNT(T_ID) AS TOTAL
FROM account ac
LEFT JOIN transaction tr ON ac.ACC_KTP_NUM = tr.T_ACC_KTP_NUM
GROUP BY ACC_KTP_NUM  
ORDER BY TOTAL ASC;

-- 4
SELECT ACC_KTP_NUM, ACC_NAME, SUM(T_PENALTY_COUNT) AS PENALTI, SUM(T_PENALTY_COUNT*LT_PENALTY) AS TOTAL_UANG_PENALTI
FROM account ac
INNER JOIN transaction tr ON tr.T_ACC_KTP_NUM =  ac.ACC_KTP_NUM
INNER JOIN loan_type lt ON lt.LT_ID = tr.T_LT_ID
WHERE T_PENALTY_COUNT <> 0
GROUP BY ACC_KTP_NUM
ORDER BY TOTAL_UANG_PENALTI

-- 5
SELECT ACC_NAME
FROM account
WHERE ACC_KTP_NUM NOT IN (
SELECT DISTINCT T_ACC_KTP_NUM
FROM transaction)