-- 1
SELECT T_ID, T_DATE
FROM Transaction
WHERE MONTH(t_date) <= 6 AND YEAR(t_date) = 2021;

-- 2
SELECT ACC_NAME, T_DUE_DATE
FROM account
INNER JOIN transaction
ON T_ACC_KTP_NUM = ACC_KTP_NUM
WHERE T_STATUS = 'BELUM LUNAS'
AND T_DUE_DATE < '2022-12-29';

-- 3
SELECT LT_NAME_ID,COUNT(T_LT_ID) AS Banyak_Transaksi
FROM transaction,loan_type
WHERE LT_ID = T_LT_ID
GROUP BY LT_ID;

-- 4
SELECT T_ID, T_LOAN, SUM(T_MONTHLY_PAYMENT) AS TOTAL_PAYMENT
FROM transaction INNER JOIN loan_payment
ON T_ID = LP_T_ID
GROUP BY T_ID
ORDER BY TOTAL_PAYMENT DESC;

-- 5
SELECT ROUND(AVG((TIMESTAMPDIFF(YEAR,ACC_DATE_OF_BIRTH,NOW()))),2) AS "UMUR RATA RATA"
FROM account
WHERE ACC_KTP_NUM IN (
    SELECT DISTINCT T_ACC_KTP_NUM
    FROM transaction );